### ISSUE TITLE
Ambiguous letters detection with help of CNN

### ISSUE THREAD

**Issue by FrightenedFox** [knmlprz/mallicious-url-model#21]
*This should have been a draft pull request, but they are not available with private repos and our GitHub plan.*

### **Motivation**

A model which can distinguish `allegro.pl` from `a11egro.pl` is necessary for the presentation, but our model can not really do that. I assume this problem is unsolvable for any metric-based ML algorithm and sometimes even for a human just because there are hundreds of legit pages with numbers in the TLD (e.g. [3blue1brown](https://www.3blue1brown.com/) or [9to5google](https://9to5google.com/)). We have discussed earlier that there are two ways of solving this problem: by searching the legitimate data set for links with similar characters or by using some advanced searching algorithm that would ignore them. I'm not sure how to implement letter one, so I've started with the former. 

To begin with, we need to find similar UTF-8 characters, but, since there are more than 1 000 000 UTF-8 symbols, doing so by hand is not very efficient. That is why I've decided to write a CNN classifier, which would allocate all UTF-8 symbols into 26 categories ( = 26 letters of the English alphabet). I'm not sure whether this is a good idea, but I'm excited to find out.s.

### **Tasks**

- [x] A data set with images of English letters in different fonts is required. *(The `/Notebooks/ambiguous-letters-detection/generate_letters_dataset.ipynb` notebook on the `ambiguous-letters-detection` branch provides one with 300 images per letter)*  
- [ ] The CNN should be implemented. *(I'm currently working on it)*  
- [ ] The CNN should be tested on some UTF-8 characters which are obviously similar to some English equivalents (e.g. `0`-`o`, `ą`-`a`, `р`-`р` (the first 'p' is from сyrillic alphabet) etc.)
- [ ] If the algorithm passes the test successfully, further actions will be taken...

What are your thoughts on this? Is it a good idea?
